config/routes.rb
Rails.application.routes.draw do
  resources :quotes

  root 'quotes#index'

end

app/models/quote.rb
class Quote < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: [:show, :edit, :update, :destroy]

  # GET /quotes
  # GET /quotes.json
  def index
    @quotes = Quote.all
  end

  # GET /quotes/1
  # GET /quotes/1.json
  def show
  end

  # GET /quotes/new
  def new
    @quote = Quote.new
  end

  # GET /quotes/1/edit
  def edit
  end

  # POST /quotes
  # POST /quotes.json
  def create
    @quote = Quote.new(quote_params)

    respond_to do |format|
      if @quote.save
        format.html { redirect_to @quote, notice: 'Quote was successfully created.' }
        format.json { render :show, status: :created, location: @quote }
      else
        format.html { render :new }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotes/1
  # PATCH/PUT /quotes/1.json
  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html { redirect_to @quote, notice: 'Quote was successfully updated.' }
        format.json { render :show, status: :ok, location: @quote }
      else
        format.html { render :edit }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1
  # DELETE /quotes/1.json
  def destroy
    @quote.destroy
    respond_to do |format|
      format.html { redirect_to quotes_url, notice: 'Quote was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quote_params
      params.require(:quote).permit(:author, :quote, :background)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myquotes2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="container">
  

<%= yield %>

</body>
</html>

app/views/quotes/_form.html.erb
<%= form_for(@quote) do |f| %>
  <% if @quote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quote.errors.count, "error") %> prohibited this quote from being saved:</h2>

      <ul>
      <% @quote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :author %><br>
    <%= f.text_field :author, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :quote %><br>
    <%= f.text_area :quote, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :background %><br>
    <%= f.text_area :background, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/quotes/edit.html.erb
<h1>Editing Quote</h1>

<%= render 'form' %>

<%= link_to 'Show', @quote, class: "btn btn-info"   %> |
<%= link_to 'Back', quotes_path, class: "btn btn-info"   %>

app/views/quotes/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Listing Quotes</h2>
<h4>Authors and Quotes possibly with some Background information...</h4>
<div class="panel panel-group">

    <% @quotes.each do |quote| %>
        <div class="panel panel-default">
          <div class="panel-heading"><h6><%= quote.author %></h6></div>
          <div class="panel-body"><h4><%= quote.quote %></h4></div>
          <div class="panel-footer"><h6><%= quote.background %></h6></div>
            <a><%= link_to 'Show', quote , class: "btn btn-primary" %></a>
            <a><%= link_to 'Edit', edit_quote_path(quote) , class: "btn btn-info" %></a>
            <a><%= link_to 'Destroy', quote, method: :delete, data: { confirm: 'Are you sure?'}, class: "btn btn-danger" %></a>
        </div>
    <% end %>
</div>

<br/>

<%= link_to 'New Quote', new_quote_path, class: "btn btn-info"   %>

app/views/quotes/new.html.erb
<h1>New Quote</h1>

<%= render 'form' %>

<%= link_to 'Back', quotes_path, class: "btn btn-info"  %>

app/views/quotes/show.html.erb
<p id="notice"><%= notice %></p>
<div class="panel panel-group">
  <div class="panel panel-default">
<p class="panel-heading">
  <strong>Author:</strong>
  <%= @quote.author %>
</p>

<p class="panel-body">
  <strong>Quote:</strong>
  <%= @quote.quote %>
</p>

<p class="panel-footer">
  <strong>Background:</strong>
  <%= @quote.background %>
</p>
  </div>
</div>
<%= link_to 'Edit', edit_quote_path(@quote), class: "btn btn-info"   %> |
<%= link_to 'Back', quotes_path, class: "btn btn-info"   %>